version: 0.1

env: 
  variables:
    PROPERTIES_FILE: "application-aws.properties"
    DEST_PROPERTIES_FILE: "src/main/resources/application-aws.properties"
  secrets-manager:
    MYSQL_USER: "db_creds:mysql_user"
    MYSQL_PASSWORD: "db_creds:mysql_password"
    MYSQL_DATABASE: "db_creds:mysql_database"
    MYSQL_ENDPOINT: "db_creds:mysql_endpoint"
    CODEARTIFACT_AUTH_TOKEN: "codeartifact:codeartifact_domain_token"
    CODEARTIFACT_REPO: "codeartifact:codeartifact_artifact_repo_endpoint"
    APPARTIFACT_REPO: "codeartifact:codeartifact_app_repo_endpoint"

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo "bucket name is $BUCKET_NAME "
      - echo bucket name is $BUCKET_NAME
      - echo app repo $APPARTIFACT_REPO
      - echo artifact repo $CODEARTIFACT_REPO
      - aws s3 cp s3://$BUCKET_NAME/application-aws.properties src/main/resources/application-aws.properties
      - ls -lrt src/main/resources/application-aws.properties
      - cat src/main/resources/application-aws.properties

  build:
    commands:
      - echo Build started on `date`
      - mvn clean deploy -s settings.xml 
      - cp target/SpringDataTest-0.0.1-SNAPSHOT.jar codedeploy 
      - ls -lrt codedeploy
      - cd codedeploy && zip -r ../info.zip * 
      - ls -lrt info.zip
      
artifacts:
  files:
    - info.zip
  discard-paths: yes

