version: 0.1

env: 
  variables: 
    PROPERTIES_FILE: "application-aws.properties" 
    DEST_PROPERTIES_FILE: "src/main/resources/application-aws.properties" 
  secrets-manager: 
    DB_USER: "db_creds:mysql_user"
    DB_PASSWORD: "db_creds:mysql_password"
    DB_DATABASE: "db_creds:mysql_database"
    DB_ENDPOINT: "db_creds:mysql_endpoint"
phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo "Creating application-aws.properties file"
      - echo "spring.datasource.url=jdbc:mysql://$DB_ENDPOINT/$DB_DATABASE" >> ${PROPERTIES_FILE}
      - echo "spring.datasource.username=$DB_USER" >> ${PROPERTIES_FILE}
      - echo "spring.datasource.password=$DB_PASSWORD" >> $PROPERTIES_FILE
      - echo "spring.jpa.hibernate.ddl-auto=none" >> $PROPERTIES_FILE
      - echo "spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl" >> $PROPERTIES_FILE
      - echo "spring.jpa.properties.hibernate.id.new_generator_mappings=false" >> $PROPERTIES_FILE
      - echo "spring.redis.host=redis" >> $PROPERTIES_FILE
      - echo "spring.redis.port=6379" >> $PROPERTIES_FILE
      - cat $PROPERTIES_FILE
      - echo cp $PROPERTIES_FILE $DEST_PROPERTIES_FILE
      - cp $PROPERTIES_FILE $DEST_PROPERTIES_FILE
      - cat $DEST_PROPERTIES_FILE
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      
artifacts:
  files:
    - target/SpringDataTest-0.0.1-SNAPSHOT.jar

